name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7 ,3.8, 3.9, '3.10', 3.11]
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Checkout github repo (+ download lfs dependencies)
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[test]
    - name: Download and extract test data
      run: |
        wget https://cardiac.nottingham.ac.uk/syncropatch_export/test_data.tar.xz -P tests/
        tar xvf tests/test_data.tar.xz -C tests/
    - name: Test with pytest
      run: |
        python -m pip install -e .
        python -m pytest --cov --cov-config=.coveragerc
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
    - name: Lint with flake8
      run: |
        python -m flake8 pcpostprocess/*.py tests/*.py
    - name: Import sorting with isort
      run: |
        python -m isort --verbose --check-only --diff pcpostprocess tests setup.py
